### ISSUE TITLE
Interactive map/data

### ISSUE THREAD

**Issue by DheekshuKumar** [CovEducation/CovEd#74]
Outreach requested a map or data about how many mentors we have, and how many students we have that can be on our homepage

**Comment by oupadhyay** [comment]
Just making sure; are we just putting say circles over the location of mentors and mentees? Because putting more information about where a certain mentor/mentee leaves seem like a data privacy issue. Another way is to split up the US into states/counties and display the number of mentees/mentors from each state/county. Which are we attempting?

**Comment by johancc** [comment]
Sure circles are good enough for now. @DheekshuKumar We're not collecting any location info, so how about just a live count of mentor & mentees & maybe how many matches have been made?

**Comment by DheekshuKumar** [comment]
Yeah -- I wrote the request because that's what Outreach requested, but I agree that what we really want is the big live count numbers of mentors and mentees.
