### ISSUE TITLE
desktop and mobile always has a scroll bar

### ISSUE THREAD

**Issue by kat-y** [CovEducation/CovEd#83]
Seems to have some resizing issues with viewed on desktop chrome and emulating ipad/pixel/other mobile devices has the same issue (even if fullscreen the left-right scroll bar is slightly smaller than the width of the page, there’s borders on both sides that you scroll to reach, text gets cut off)

**Comment by johancc** [comment]
Can I have a picture for this? Not sure on which page / how to replicate this issue

**Comment by kat-y** [comment]
![image](https://user-images.githubusercontent.com/60154020/80922456-3a654380-8d4b-11ea-9952-26991fd78c26.png)
![image](https://user-images.githubusercontent.com/60154020/80922467-4a7d2300-8d4b-11ea-8b69-f968544e6d31.png)

**Comment by DheekshuKumar** [comment]
I feel like I fixed this at some point but @kat-y can you check if you're still having the issue?

**Comment by johancc** [comment]
If you still have issues you just have to set the width of the App-container to 100% I think

**Comment by kat-y** [comment]
@DheekshuKumar still having this issue 
![image](https://user-images.githubusercontent.com/60154020/83053191-5ee8ce80-a01e-11ea-88ef-b278920a89fb.png)

**Comment by oupadhyay** [comment]
## Confirmation
I can confirm that when I view it, there is a bottom scrollbar. It seems that the width is **slightly bigger** the window width. Zooming on the tab does **not** affect it and only changes the _size of the content_ rather than the entire website. 

### A GIF

![CovEducation](https://user-images.githubusercontent.com/46334571/83985164-f25ab300-a8ec-11ea-9396-813d3169b957.gif)
